# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
# azure-pipelines.yml
trigger:
  branches:
    include:
      - main # Adjust to your main branch name

pool:
  vmImage: 'ubuntu-latest'

variables:
  SDK_VERSION: '30'
  GRADLE_VERSION: '7.0.2'
  ANDROID_BUILD_TOOLS_VERSION: '30.0.3'
  MIN_SDK_VERSION: '21'
  TARGET_SDK_VERSION: '30'
  PACKAGE_NAME: 'com.example.sagecommerce'
  MAIN_ACTIVITY: 'MainActivity'
  APP_NAME: 'SageCommerceApp'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - task: Bash@3
    displayName: 'Install JDK 8'
    inputs:
      targetType: 'inline'
      script: |
        sudo apt update
        sudo apt install openjdk-8-jdk -y
        echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" >> $BASH_ENV

  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'gradlew'
      options: 'assembleDebug'
      tasks: 'build'
      publishJUnitResults: false
      workingDirectory: '$(Build.SourcesDirectory)/$(APP_NAME)'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      sonarQubeRunAnalysis: false

  - task: Bash@3
    displayName: 'Download and setup Android SDK'
    inputs:
      targetType: 'inline'
      script: |
        mkdir -p $HOME/Android/Sdk
        cd $HOME/Android/Sdk
        curl -O https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip
        unzip commandlinetools-linux-8092744_latest.zip -d cmdline-tools
        mv cmdline-tools/cmdline-tools $HOME/Android/Sdk/cmdline-tools/latest
        rm commandlinetools-linux-8092744_latest.zip

        export ANDROID_HOME=$HOME/Android/Sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
        yes | sdkmanager --licenses
        sdkmanager --install "platform-tools" "build-tools;$ANDROID_BUILD_TOOLS_VERSION" "platforms;android-$SDK_VERSION"

  - task: Gradle@2
    displayName: 'Build Android app'
    inputs:
      gradleWrapperFile: 'gradlew'
      options: 'assembleDebug'
      tasks: 'assembleDebug'
      workingDirectory: '$(Build.SourcesDirectory)/$(APP_NAME)'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.SourcesDirectory)/$(APP_NAME)/app/build/outputs/apk/debug'
      artifactName: 'apk'
      publishLocation: 'Container'